### ISSUE TITLE
Some words (actually non-words) causes panic

### ISSUE THREAD

**Issue by john5000** [surge/porter2#2]
Stem("aed") causes an error (a panic).
Seems to be from step1b where  rs[len(rs)-2] is used as an index, but len(rs)=1.
From my testing, it only happens with a vowel followed by a word ending that would be stripped, like "aed" or "aing" or "eing", etc.
Of course, those are not really words! But in real life those can show up in text anyway.
Note: despite that, porter2 is an excellent product and is very fast.

**Comment by zhenjl** [comment]
ack..will look..
